//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zdorovie
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Appel = new HashSet<Appel>();
        }
    
        public decimal oms { get; set; }
        public string fio { get; set; }
        public string seriesAndNumberPassword { get; set; }
        public decimal phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appel> Appel { get; set; }
    }
}
 public PatientPage()
        {
            InitializeComponent();
            context = new ZdorovyeEntities();
            patienttable.ItemsSource = context.Patient.ToList();     
        }
        public void RefreshData()
        {
            var list = context.Patient.ToList();

            if (!string.IsNullOrWhiteSpace(fiobox.Text))
            {
                list = list.Where(x => x.fio.ToLower().Contains(fiobox.Text.ToLower())).ToList();
            }
            if (!string.IsNullOrWhiteSpace(omsbox.Text))
            {
                list = list.Where(x => x.oms.ToString().Contains(omsbox.Text.ToLower())).ToList();
            }
            patienttable.ItemsSource = list;
        }
